dist: xenial
language: python
python:
  - 3.9
before_install:
  - python --version
  - pip install -U pip
install:
  - pip install -r requirements.txt
  - pip install codecov
  - pip install pytest-cov
script:
  - pytest --cov-report term --cov=tests/
after_success:
  - codecov