language: python
python:
  - 3.9
before_install:
  - python --version
  - pip install -U pip
  - pip install codecov
install:
  - pip install -r requirements.txt
script:
  - python3 -m unittest discover
after_success:
  - codecov